on:
  push:

jobs:
  scans:
    runs-on: ubuntu-slim
    name: Sparse commit
    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ github.ref }}

      - run: pwd && ls

      - run: mkdir -p ${{ github.workspace }}/results && touch ${{ github.workspace }}/results/$RANDOM.txt

      - uses: EndBug/add-and-commit@v10
        with:
          add: "results"
          pull: '--rebase --autostash ...'
          default_author: "github_actions"
          message: "commit"
